require: rubocop-minitest
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.0
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20
